<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?></title>
<link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('../../default/bookstore/custom.css') ?>" media="all" />
<!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body id="login_page">
    <div id="loginContainer">
    
        <div  class="login_logo">
        
        	<img src="<?php echo $this->getSkinUrl('../../default/bookstore/images/logo-login.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?>">
        
        	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        
        </div>
      <!-- /.login_logo -->
          
       <div class="login_form">
      
      	<form method="post" action="" id="loginForm">
      
        <div class="form-title">
          <h1><?php echo Mage::helper('adminhtml')->__('Forgot your user name or password?'); ?></h1>
          <h2><?php echo Mage::helper('adminhtml')->__('Insert your email to restore the password'); ?></h2>
        </div>
        <!-- /.form-title -->
        
         <input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>" />
         
         
        <div class="input-container">
         
          <input type="text" id="email" name="email" value="" class="required-entry input-text forgot-password validate-email" placeholder="<?php echo Mage::helper('adminhtml')->__('Email Address:'); ?>" required>
        </div>
        <!-- /.input-container -->
        
        <button type="submit" id="login-btn" class="btn-login"><?php echo Mage::helper('adminhtml')->__('Retrieve Password'); ?> &raquo;</button>
        
      </form>
      
      </div>

      <a class="left" href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)); ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login'); ?></a> 
      
    <!-- /.login_form -->
    
    
</div>
<!-- /#loginContainer -->
<a href="<?php echo $this->getBaseUrl() ?>" class="link-frontend"> &laquo; Back to Frontend </a>
<script type="text/javascript">
	var loginForm = new varienForm('loginForm');
</script>
</body>
</html>



