
<?php if(Mage::getStoreConfig('bookstore/header/topheader_enable',Mage::app()->getStore())==1): ?>
<!-- Top Bar -->
<div id="topbar" <?php if(Mage::getStoreConfig('bookstore/header/topheader_color1',Mage::app()->getStore())): 
echo 'style="background-color:#'. Mage::getStoreConfig('bookstore/header/topheader_color1',Mage::app()->getStore()) .'"'; endif; ?>>
<div class="container">
	<div class="row">
		<div class="col-md-8 col-sm-7"><?php //  ?>
		<?php
		if( (Mage::getStoreConfig('bookstore/header/telephone',Mage::app()->getStore())) || (Mage::getStoreConfig('bookstore/header/telephone',Mage::app()->getStore()) == '')):
			echo Mage::getStoreConfig('bookstore/header/telephone',Mage::app()->getStore());
		 else:
		   echo $this->getChildHtml('topbar_cmslinks');
		 endif;
		 ?>
		
</div>
		<div class="user-links col-md-4 col-sm-5 col-xs-6">
			<span class="welcome pull-left hidden-xs"><?php echo $this->getLayout()->getBlock('header')->getWelcome() ?></span>
			<ul class="list-inline pull-left ">
			<?php if ($this->helper('customer')->isLoggedIn()): ?>

			 <li class="account"><a title="Il mio Account" href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('My Account') ?></a></li>
			 <li class="esci"><a title="Log Out" href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Logout') ?></a></li>
			 <?php else: ?>

	 		 <li class="area"><a href="<?php echo $this->getUrl('customer/account/login/') ?>"><?php echo $this->__('Login') ?></a></li>
	         <li class="nuovo"><a href="<?php echo $this->getUrl('customer/account/create/') ?>"><?php echo $this->__('Create Account') ?></a></li>
	        <?php endif;?>

			</ul>
		</div>
	</div>
</div>
</div>
<?php endif ?>

<!-- Main Header -->
<div id="header">
	<div class="container">
		<div class="row">
			<div class="logo col-md-4 col-sm-5">
					<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
					<?php 
						if(Mage::getStoreConfig('bookstore/header/logo',Mage::app()->getStore())):
							$logourl = $media . 'media/bookstore/' . Mage::getStoreConfig('bookstore/header/logo',Mage::app()->getStore()); 
						else:  
							$logourl = $this->getLogoSrc(); 
							endif;
					?>
					<img src="<?php echo $logourl  ?>" alt="<?php echo $this->getLogoAlt() ?>" class="img-responsive" />
				</a>
			</div>

			
			
			
			
			<div class="col-md-4 col-sm-2"></div>
			<div class="col-md-4 col-sm-5">
		        <?php echo $this->getChildHtml('top_cart') ?>
		    </div>
		</div>
	</div>
</div>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-main" role="navigation">
	<div class="container">
		<div class="row">
			<div class="navbar-header">
				<a class="navbar-brand visible-xs" href="#">
				    <?php echo $this->__('Categories') ?>
				</a>
				
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
				    <span class="sr-only"><?php echo $this->__('Toggle Navigation') ?></span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				</button>
			</div>
			
			<div class="collapse navbar-collapse navbar-main-collapse">
			<?php echo $this->getChildHtml('topMenu') ?>
			<?php echo $this->getChildHtml('topSearch') ?>
			</div>
		</div>
	</div>
</nav>
