<?php if ($this->getIsNeedToDisplaySideBar()):?>

<div class="block block-cart block-topcart">
  <?php $_cartQty = $this->getSummaryCount() ?>
  <div class="block-title"><span class="glyphicon glyphicon-shopping-cart"></span><strong><span><?php echo $this->__('My Cart') ?></span></strong>
    <?php if ($_cartQty>0): ?>
    <div class="summary">
      <?php if ($_cartQty==1): ?>
      <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></p>
      <?php else: ?>
      <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></p>
      <?php endif ?>
    </div>
    <?php else: ?>
    <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
  </div>
  <!-- // block-title -->
  <div class="block-content">
    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
    <div class="actions"> <?php echo $this->getChildHtml('extra_actions') ?>
      <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
    </div>
    <?php endif ?>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
    <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
    <ol id="cart-sidebar" class="mini-products-list">
      <?php foreach($_items as $_item): ?>
      <?php echo $this->getItemHtml($_item) ?>
      <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
    <?php endif  ?>
  </div>
</div>
<?php endif;  ?>
